---
- name: update apt-cache
  sudo: yes
  apt:
      update_cache: yes
      cache_valid_time: 3600

- name: install nginx
  apt:
      pkg: "{{ item }}"
      state: present
  sudo: yes
  with_items: "{{ nginx_package }}"

- name: copy nginx config
  template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0644
  notify:
      - restart nginx

- name: delete default vhost
  file:
      path: "{{ item }}"
      state: absent
  with_items:
      - /etc/nginx/sites-enabled/default
      - /etc/nginx/sites-available/default
  notify:
      - restart nginx

- name: create vhost root directorys
  file:
      path: "{{ item.value.hostroot }}"
      state: directory
      owner: pi
      group: pi
      mode: 0755
  with_dict: nginx_vhosts

- name: create vhost config
  template:
      src: templates/vhost.conf.j2
      dest: "/etc/nginx/sites-available/{{ item.value.hostname }}"
      owner: pi
      group: pi
      mode: 0755
  with_dict: nginx_vhosts
  notify:
      - restart nginx

- name: enable vhosts
  file:
      src: "/etc/nginx/sites-available/{{ item.value.hostname }}"
      dest: "/etc/nginx/sites-enabled/{{ item.value.hostname }}"
      state: link
  with_dict: nginx_vhosts
  notify:
      - restart nginx

- name: copy first page to vhost
  template:
      src: templates/index.html.j2
      dest: "{{ item.value.hostroot }}/index.html"
      owner: pi
      group: pi
      mode: 0644
  with_dict: nginx_vhosts
