---
- name: update apt-cache
  sudo: yes
  apt:
      update_cache: yes
      cache_valid_time: 3600

- name: install nginx
  apt:
      pkg: "{{ item }}"
      state: present
  sudo: yes
  with_items: "{{ nginx_package }}"
